[package]
name = "fhir"
description = "HL7 FHIR data models"
version = "0.0.1"
edition = "2021"
authors = ["Balamurali Pandranki <balamurali@live.com>"]
documentation = "https://docs.rs/fhir"
readme = "README.md"
repository = "https://github.com/itsbalamurali/rust-fhir"
license-file = "LICENSE"

[dependencies]
bytes = "1.1.0"
prost = { version = "0.10.1", features = ["prost-derive"] }
prost-types = "0.10"
prost-wkt = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
prost-build = { version = "0.10.1" }
quote = "1.0"
convert_case = "0.5"
prost = "0.10.1"
prost-types = "0.10.1"
