[package]
name = "fhir"
version = "0.1.0"
edition = "2021"


[dependencies]
bytes = "1.1.0"
prost = { version = "0.10.1", features = ["prost-derive"] }
prost-types = "0.10"
prost-wkt = "0.3.1"
prost-wkt-types = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
[build-dependencies]
prost-build = { version = "0.10.1" }
prost-wkt-build = "0.3.1"