name: Generate
on:
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Rust Cache
      uses: Swatinem/rust-cache@v1

    - name: Clone Google FHIR Protobufs
      run: git clone https://github.com/google/fhir

    - name: Rust Build
      run: cargo build
      
    - name: Update Repository
      uses: EndBug/add-and-commit@v9
      with:
          author_name: Balamurali Pandranki
          author_email: balamurali@live.com
          default_author: github_actor
          message: 'Generated code.'
          push: true